### PR TITLE
fix: revert icons to simple decoration

### PR DESCRIPTION
**Pull request by ramboz**
Moving https://github.com/adobe/helix-project-boilerplate/pull/253/ over to the new repo.

## Description

Most customers directly use svg icons as they were exported by their preferred application (Illustrator, etc.), and that markup isn't compatible with the spriting logic in most cases. On top of that, the current spriting implementation has required frequent patching and isn't likely that stable yet. As such, we want to revert to basic icons decoration by default, and move the spriting to the block party instead until it is considered mature enough.

Test URLs:
- Before: https://main--aem-lib--adobe.hlx.page/
- After: https://simplify-icons--aem-lib--adobe.hlx.page/

## Related Issue

- https://github.com/adobe/helix-project-boilerplate/pull/192
- https://github.com/adobe/helix-project-boilerplate/pull/213
- https://github.com/adobe/helix-project-boilerplate/pull/220
- https://github.com/adobe/helix-project-boilerplate/pull/241
- https://github.com/adobe/helix-project-boilerplate/pull/256

## Motivation and Context

For the spriting to really work, it requires:
1. that icons leverage `currentcolor`
2. that icons not be styled (no `<style>` tag or `class` attributes)
3. that all identifiers be properly scoped to avoid clashes between different icons
4. that icon sizes be specifically applied via CSS

All of which require developer involvement and do not apply to the basic use cases. Hence we want to simplify the reference implementation and rather move the spriting approach to the block party.

## How Has This Been Tested?

This is how the behavior used to be before we introduced the spriting logic. Additionally, this has been tested against the boilerplate, and also with BambooHR's icon-heavy pages which initially triggered the spriting discussion

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by kptdobe** [comment]
Nice, thanks @ramboz!

**Review by kptdobe — APPROVED** [review]

**Comment by kptdobe** [comment]
I still think we could integrate the test from https://github.com/adobe/aem-lib/pull/12 - the method is not async anymore which somehow invalidates the test, I agree but for backward compatibility of the code, I still think it could be good to just add the test.

**Comment by ramboz** [comment]
Sure, it will make it both back/forward compatible in a sense and guarantee the behavior even if we iterate over the implementation. We do have to remove the sprite-related checks from the test though

**Comment by kptdobe** [comment]
Yes, of course, the test has to be adapted to the new implementation. I was more referring to the "concurrent" aspect, just to be sure it does not break if you load the same icon twice in parallel!

**Comment by ramboz** [comment]
@kptdobe Are you guys handling the merge here, or should I just go ahead?

**Comment by kptdobe** [comment]
I would prefer to integrate the tests from #12 in the PR so that we have a better coverage right for the beginning.
I have also seen you reference a bunch of issue in the description like https://github.com/adobe/helix-project-boilerplate/pull/192. Maybe adding a test for each of them (or make sure they are covered by a test) before merging would be awesome.

**Review by kptdobe — CHANGES_REQUESTED** [review]
Changing my PR review to increase the test coverage based on the list of issues mentioned in the PR description.

**Comment by ramboz** [comment]
I'm not sure any of those would really apply anymore. They were specific edge cases with the SVG sprite implementation. So more white-box tests than black-box ones. and the last one is already covered by #12

**Review by kptdobe — APPROVED** [review]
ok, let's merge it and continue from here!

**Pull request merged**
